project_id = "kweiptzbmsbifplynnpb"

[functions.send-notification]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.check-compliance-expiry]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.send-crm-email]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false

[functions.public-enquiry]
verify_jwt = false

[functions.inbound-email-webhook]
verify_jwt = false

[functions.xero-auth]
verify_jwt = false

[functions.xero-sync]
verify_jwt = false

[functions.send-recovery-email]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.email-tracking-pixel]
verify_jwt = false
